[package]
name = "aoc_2024"
version = "0.1.0"
edition = "2021"
authors = ["Matthew Pocock <turingatemyhamster@gmail.com>"]

[lib]
bench = false

[dependencies]
rust-crypto = "0.2.36"
aoc-runner = "0.3.0"
aoc-runner-derive = "0.3.0"
regex = "1.11.1"
nom = "7.1.3"